version: '3.8'
name: backend
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - shared

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - shared

volumes:
  postgres:
    name: postgres-volume

networks:
  shared:
    driver: bridge
